tninja/aider.el

- aider.el
Functions from `comint` and `which-func` is used, so we should require them in case they are not loaded before `aider`.
> fix: require needed packages

- aider.el
Entry commands should be autoloaded, so if the user use some package manager that generates the autoload file, they can defer loading of `aider.el` until the entry command is used.
> enh: autoload the entry command

- aider.el
The single quote `'` is converted to a right single quote in the `*Help*` buffer, and the backtick is converted to left single quote. But use single quotes may cause the misunderstanding that `aider` is an elisp symbol, so I use double quotes instead.
P.S. To get a straight quote in the `*Help*`buffer, use `\\='` in the docstring.
> doc: fix quote usage in docstring

- aider.el
It may not be a typical scenario to modify the aider program name, but it helps users who don't have a system-wide aider installation. Or if one wants to route the traffic through some network proxy, they can abuse these options:
```lisp
(setq
aider-program "proxychains4"
aider-args '("-q" "aider" other-arguments...))
```
> feat: custom option of aider program

- aider.el
Added two interactive functions:
1. aider-batch-add-dired-marked-files: user can mark multiple files inside dired buffer (it can also be a find-name-dired output buffer). and call these function to batch add multiple files
2. aider-ask-question-under-cursor: user can have a aider question specific file, write down question there, and call this function to send the question under cursor to aider buffer.
> Feat: Add aider-ask-question-under-cursor and aider-batch-add-dired-marked-files function

- aider.el
This PR does two things:
First, it hardcodes the terminal setting to dumb. This is the default, but if the user happens to be using a different setting (as I am) then it will break aider since it is built on prompt-toolkit.
Second, Aider will output a series of Unicode dashes between the prompts. However, it doesn't query for the correct size and instead just hardcodes the number of dashes to insert. Emacs already has a nice way to handle these separators via `page-break-lines`. This has the advantage that it will always span the entire window, even when resizing.
> Fix terminal setting and use separator between prompts

- README.org
- aider-doom.el
To address feedback in https://github.com/tninja/aider.el/issues/16
> change aider prefix for DOOM emacs from l to A

- aider-helm.el
- aider.el
Eg. if the initial buffer major mode is emacs-lisp-mode, the aider buffer will highlight emacs lisp keyword; if initial buffer major mode is python-mode, the aider buffer will highlight python keyword
also bring back the ###autoload, and increase aider-helm.el history size limit
> Feat: Highlight the comint buffer based on initial buffer major mode

- README.org
- aider.el
As described at https://github.com/tninja/aider.el/issues/36
Thanks @artyom-smushkov for the feedback and the solution to this
The change require emacs 26.1
> Fix: Make aider.el work with tramp

- aider.el
The `aider-add-or-read-current-file` function was incorrectly constructing the command to add a file to the aider chat, always using the `/add` prefix regardless of the value of `aider--add-file-read-only`.
This commit fixes the issue by ensuring that the function correctly uses the prefix returned by `aider--get-add-command-prefix`, which will be `/read-only` when `aider--add-file-read-only` is non-nil.
Specifically, the following changes were made:
- Modified `aider-add-or-read-current-file` to use the `command-prefix` argument when constructing the command string.
- Updated `aider-add-current-file` to pass the result of `aider--get-add-command-prefix` to `aider-add-or-read-current-file`.
This ensures that files are added with the correct prefix based on the user's configuration, …
> Fix: Use correct prefix in aider-add-or-read-current-file

- README.org
- aider-doom.el
- aider.el
It is useful when we need to describe the design in multiple lines in a design doc, and ask aider to implement the design.
> Feat: Add aider-send-region function

- README.org
- aider.el
[…l/issues/23](https://github.com/tninja/aider.el/issues/23),
Try to make aider working on different git submodules synchronously. It works for my local testing.
> git_repo_path works for submodules.

- README.org
- aider-doom.el
- aider.el
1. Don't auto switch to buffer when send line to it. (cause we might need to other things)
2. C-c C-n will send region line by line, if a region selected.
3. C-c C-z will switch to aider session buffer, key binding is as same as ESS
> Feat: update for aider-minor-mode

- README.org
Fixes:
- Straight might not be installed, provided alternative using package-vc-install
- missing semi colon on config example.
> Add instructions to install without straight, fix missing comment.

- README.org
For users who have already configured aider in `~/.aider.conf.yml`, this suggestion allows them to use this and not have to pass multiple other arguments.
> Suggest using user's `~/.aider.conf.yml`

- README.org
- aider.el
This PR offers the user to use the universal argument to change the content of `aider-args` before running aider.
So they can use:
- `C-c a C-u a`
- `C-u M-x aider-run-aider`
- or `C-u` before any keybind you might have
> Using universal argument prompts user to change `aider-args`

- aider-doom.el
Byte-compiling aider-doom.el fails unless Doom's `map!` macro is defined first. Doom defines this as part of its initialization, but it is not normally defined when byte-compiling: even when installing aider-doom.el using Doom, Doom byte-compiles packages in a separate process (without itself loaded) and is just ignoring the failure to byte-compile this file.
This does no harm when aider-doom.el is used by Doom, but can be an annoyance when packaging aider.el using something that fails on byte compilation failures by default (see
https://github.com/marienz/nix-doom-emacs-unstraightened/issues/50).
Since byte-compiling this file will (normally) fail anyway, explicitly disable it.
> Don't try to byte-compile aider-doom.el

- aider.el
- test_aider.el
When current buffer file is not associated with a git repo, it should still be able to start the aider session with aider-run-aider.
Aider itself is able to do that and ask if we want to init the git for the dir.
> Fix: Handle the case when the current buffer file is not in a git repo

- aider-helm.el
If helm is not installed, it was causing `aider-read-string` to be undefined breaking many of the functionality.
This checks if it is installed prior to overwriting
tested on Emacs v29.4
> feat: Add helm feature check before overriding aider-read-string

- aider.el
Addressing https://github.com/tninja/aider.el/issues/81
> fix: Normalize paths for unique Aider buffer names using file-truename

- aider.el
I added aider--infix-add-file-read-only before, People mentioned that aider-current-file-read-only is more preferred. And I don't really feel that is very smooth to use. To simplify the menu, want to remove that. (will also simplify the file add related functions in future).
dup key described in https://github.com/tninja/aider.el/issues/87.
> Refactor: remove aider--infix-add-file-read-only, add aider-drop-current-file, and fix dup short key in menu

- aider.el
Currently, if you enter a multi-line prompt and try to send it, Aider will interpret it as multiple commands. We can ensure that multi-line inputs are always properly wrapped in begin/end tags.
See #51
> Handle multi-line input in the aider buffer

- README.org
- aider.el
So that the programming language syntax color will match the most recently aider.el used source code, no need to restart aider session.
Also tweaked some text
> Feat: Move programming language syntax color rendering from aider-run-aider to aider-switch-to-buffer

- README.org
- aider-core.el
- aider-file.el
- aider-prompt-mode.el
- aider.el
The key C-c C-y will put /add to the line the cursor located, if there is no command ahead; otherwise, it will cycle through /add, /read-only, /drop. 
After we are happy about it, use C-c C-b to send these file command one by one to aider session.
The PR also improve the git diff file generation. Now it can pull change for a given commit sha.
> Feat: Add magit rebase style file operation in aider-prompt-mode, and send block line by line command

- aider-core.el
It turns out that minibuffer history variables will be saved automatically without being added to svaehist-additional-variables.
> refactor: Remove redundant savehist configuration

- aider-code-change.el
- aider-core.el
- aider-discussion.el
- aider-helm.el
- aider-prompt-mode.el
- aider.el
After this change, aider-ask-question (Question on Context), aider-general-question (Question without Context) and aider-function-or-region-refactor (Change function / region) provide a list of prompt candidates respectively, to reduce the typing effort for common code understanding / code refactoring task.
> Feat: aider-helm-read-string-with-history accept candidate prompt list

- HISTORY.org
- README.org
- aider-code-change.el
- aider-core.el
- aider-file.el
Previously I thought it works until really use it by myself on large repo.. The issue is that after start the aider in a git sub directory, add file with aider-action-current-file won't work, because currently aider.el use full path of source code file, and aider refuse to accept that with --subtree-only mode (sounds like inconsistent?). Instead, relative file path from git root works for both of w/wo of -subtree-only. This fix is about to use relative path instead when use git
Also updated FAQ about how to use --subtree-only.
Addressing https://github.com/tninja/aider.el/issues/23
> Fix: Support --subtree-only properly for large repo

- README.org
The file listing is incomplete and the example no longer works. Straight's default
value for ':files' includes '*.el' so it'll load all the needed files.
> Remove the file listing for the setup with straight

- HISTORY.org
- aider-code-read.el
- etc/aider-etc.el
- test/test-aider.el
It now accept a module directory provided by user, /read-only <dir>, and then analyze the module using the prompt.
> Fix: aider--analyze-module function

- README.org
I had to add this in order to get the Aider keybindings enabled on startup. It's very possible I'm doing something wrong, but I thought I'd make a PR just in case!
> Update Doom instructions in README.md

- HISTORY.org
- README.org
- aider-agile.el
- aider-core.el
- aider-discussion.el
- aider-prompt-mode.el
During using aider.el, it is found that --subtree-mode was useful for large repo, and it would be great if there is a **reproducible way** to start aider with --subtree-mode in a particular directory (there are ways to do it but require more manual operations). Example use cases: Multiple feature changes need to work in same sub-module, are it would be great to have a way to easily start aider session with this setting in new feature change work. 
To address this problem, subtree-only command in aider prompt file is introduced, to start aider session given target directory (relative path to git root).
The way to use this command is:
```
subtree-mode <dir>
```
And the whole command block might looks like:
```
* My task on sub-module <dir>
subtree-mode <dir>
/read-only <file1>
/add <file2> …
```
> Add subtree-only command to aider-prompt-mode

- HISTORY.org
- aider-core.el
They are basically from the line and after that in this PR: https://github.com/MatthewZMD/aidermacs/pull/119/files#diff-1865a6c95bb14150b7acdc358d45da54237ced17219de644e1194b6e1bcab04eR387
Thanks @CeleritasCelery 
I tried and it can resolve https://github.com/tninja/aider.el/issues/126. @ahyatt would be great if you can test it from this branch.
I admit that I have little knowledge on these magic. And seems LLMs know some but cannot guarantee to be a stable expert.
> Fix: Better color rendering for aider-comint-buffer, especially on prompt input line

- HISTORY.org
- README.org
- aider-core.el
- aider-file.el
It will pull the changes of staged files, as staged.diff, and open it. Run the command second time will review that diff. The idea came from https://github.com/ragnard/gptel-magit/blob/main/gptel-magit.el#L96.
Also refactor the code review function since it has grown very large, with C-c a R (LLM suggest the refactoring strategy and I go ahead to accept it).
> Feat: aider-pull-or-review-diff-file support pull changes for magit staged files, as default option

- aider-discussion.el
- aider.el
The command is useful discuss with aider on some code, or ask aider to do trouble shooting. The copied text can be useful as part of the note / investigation report.
Also merge the Question on Function/Region and Question without Context as a single menu item, to release more menu item space.
> Feat: Expose aider /copy command as a menu item

- HISTORY.org
- snippets/aider-prompt-mode/create-tests
- snippets/aider-prompt-mode/create-unit-tests
- snippets/aider-prompt-mode/diff-change
An useful pattern of code change with aider.el is:
1. use aider-pull-or-review-diff-file (C-c a v) to pull the diff of a previous change, as a diff file
2. ask aider to suggest change given the change example in that diff file, change made somewhere else but similar to change in that diff file
3. review the change suggestion, give feedback to aider with more /ask command
4. go ahead to accept the suggestion and let aider make the change.
This PR add diff-change aider code snippet for this pattern. It can be used in aider prompt file or other file after active aider-prompt-mode, use C-n to run each line of command there.
> Feat: Add diff-change aider code snippet

- HISTORY.org
- README.org
- README.zh-cn.org
- aider.el
Given upgrading of https://github.com/magit/transient/blob/main/CHANGELOG#v090----2025-06-01
The version contains transient-define-group macro
cc @Spike-Leung
> chore: rely on stable version (0.9.0) of transient

- HISTORY.org
- README.org
- aider-core.el
Addressing https://github.com/tninja/aider.el/issues/177, to support multiple chats for the same repository.
The way in this PR, is to create git repo + feature branch specific aider session. **If we want to switch to work on a different feature, we switch git branch, and it will map to a corresponding aider session.** The aider session name pattern would be `*aider:<path-to-git-repo>:branch-name* `
> feat: Add option for branch-specific aider buffers

- HISTORY.org
- aider-core.el
- aider-prompt-mode.el
Resolve https://github.com/tninja/aider.el/issues/179, cc @Spike-Leung 
Following screenshot show completion in aider-comint-session.
Same completion will also be triggered from aider prompt file.
> Feat: /drop command file completion only list files been /add or /read-only

- README.org
- aider-agile.el
- aider-bootstrap.el
- aider-code-change.el
- aider-core.el
- aider-discussion.el
- aider-file.el
- aider-git.el
- aider-software-planning.el
- aider.el
- appendix.org
- etc/aider-etc.el
For example, do not show additional message. If aider--send-command failed, that function will show message to user and shouldn't be overwrite.
> Fix: Do not run following commands if aider--send-command failed.

- HISTORY.org
- aider-discussion.el
- aider-file.el
- aider.el
Context size of LLM are increasing, and the price per token are dropping. Adding more relevant files as context is potentially useful for aider AI coding with low cost.
Currently aider need user to add relevant file through /add or /read-only manually. This PR suggest a semi-automatic way. It add current file and its dependencies/dependents to aider session. Given current buffer source code file, figure out the source code files that depend on it, and the source code files it depends on.
> Feat: Add aider-expand-context-current-file

- aider-agile.el
- aider-comint-markdown.el
- aider-core.el
- aider-prompt-mode.el
- aider-utils.el
aider-core.el grow large and less easy to maintain / develop. This refactor is about to make code more modular.
> Refactor: Move functions from aider-core.el to aider-util.el and aider-comint-markdown.el

- aider-git.el
In case user want to understand git commits related to a particular topic
> Feat: add optional keyword filter to git log analysis in aider-magit-log-analyze

- HISTORY.org
- README.org
- README.zh-cn.org
- aider-code-change.el
- aider-core.el
- aider-doom.el
- aider.el
- appendix.org
This new feature is similar to existing aider-implement-todo, the difference is aider-implement-todo is about to add new code, aider-function-or-region-change is to modify existing code. To use this feature, user just need to:
1. Write a single line comment to describe the desired change for the current function (if the comment is in a function), or change on current added files (outside of a function). Example below:
2. When the cursor is on the comment, type C-c a r, it will compose a prompt given the requirement in the comment, and then send to aider
3. Review the code change, and accept it if you are happy with it.
This change unified the ways to input requirement with inline comment to 1. add new code; 2. modify existing code. It simplify the input interface. 
The prompt will also be …
> Feat: aider-function-or-region-change (C-c a r) support inline comment based existing code change requirement

- HISTORY.org
- README.org
- aider-code-change.el
- aider.el
- appendix.org
- etc/aider-etc.el
Following example of aider-ask-question: https://github.com/tninja/aider.el/pull/208, simplify regular code change functions to only two:
1. aider-code-change (C-c a c) to change existing code with review process (the one in this PR)
2. aider-implement-todo (C-c a i) to add new code (also with review process)
> Chore: Integrate aider-function-or-region-change and aider-architect-discussion

- aider-file.el
as list* is deprecated.
fixes #216
> chore: replace list* with cl-list*

- aider-core.el
Work around for https://github.com/tninja/aider.el/issues/219 before figuring out root cause.
> Chore: make markdown-mode rendering optional
