aider.el
It will add all opened buffers in current window to aider. Eg. class and corresponding test class
=> Feat: new function - aider-add-files-in-current-window

aider-helm.el
I feel this helm based prompt input way is also useful for other LLM emacs plugin, such as, copilot-chat.el. So we refactor and extract common logic out so that it can be reused for other purpose.
It hide the history variable, and always r/w the history el file when input got triggered, it is a little bit waste of i/o but code is simpler
=> Feat: Refactor aider-helm.el to make it more generic and reusable

README.org, aider-helm.el, aider.el
aider-function-refactor, added to menu.
also allow the helm input function accept initial-input
=> Feat: easily refactor the function under cursor

README.org, aider.el
TDD is one of the critical practice of Agile development. It could be very useful for AI assisted programming, to keep ourselves safe and be confident on AI generated code.
Some posts about TDD and AI programming:
1. https://medium.com/@divyarajsinhdev/test-driven-development-with-ai-the-right-way-to-code-using-generative-ai-8013ddb91c7a
2. https://www.thoughtworks.com/en-us/insights/blog/generative-ai/tdd-and-pair-programming-the-perfect-companions-for-copilot
In this PR, I just added a function, aider-fix-failing-test-under-cursor. It can be used when some test failed, which means source function need to be updated. Before using that, the source code file and test file should have been added to aider session. Put the cursor inside the failed function body and trigger this function …
=> Feat: Basic support for Test Driven Development (TDD)

README.org, aider-etc.el, aider.el
Also added aider-add-same-type-files-under-dir function. for batch add same types of files (eg. all .py file?) under the directory.
Thanks gemini 2.0 with large context and free api, now adding more files are possible and free.
=> Refactor: Merge some dup code, move less used functions to aider-etc.el. Update the menu.

aider.el
It is very useful, after several loop of discussion (question) with aider, after confirm the change, use this command to apply the change.
=> Feat: Add "Go Ahead" menu item

aider.el
Fix for https://github.com/tninja/aider.el/issues/51
=> Fix: error happens during sending large multi-line region

README.org, aider.el
It can implement the comment under cursor, if there is.
=> Feat: Enhance aider-implement-todo

README.org, aider-doom.el, aider.el, examples/battleship/fleet.py, examples/battleship/game.py, examples/battleship/test_game.py
Given aider support on o3-mini model: https://github.com/Aider-AI/aider/blob/main/HISTORY.md#aider-v0730
Want to see how strong it is.
The previous battleship AI is written by claude sonnet 3.5: https://github.com/tninja/aider.el/blob/main/examples/battleship/game.py#L168
This PR use o3-mini, --reasoning-effort=high to write a "HardComputerPlayer", and let it battle with previous Computer
Turns out "HardComputerPlayer" can win 69%, on a 10x10 board with 5 ships, and it can win around 55%, on a 7x7 board with 5 ships
So o3-mini (high) written AI is better than claude one.
=> doc: Add hard mode for battleship game using o3-mini high model

aider-doom.el
Personally I feel test function can be very useful on validate of AI generated code. So I also add them to doom menu
=> feat: Add Test submenu with unit test commands in aider-doom-setup-keys

README.org, aider.el, tests/test-aider-alias.el
Also applied eval-and-compile to the defalias
=> doc: Improve README tutorial

.github/workflows/release.yml, HISTORY.org, aider-code-change.el, aider-core.el, aider-file.el, aider.el
Couple of small changes. Detail in HISTORY.org
=> Feat: v0.5.5

HISTORY.org, README.org, aider-code-change.el, aider-core.el, aider-file.el, aider-helm.el, aider-prompt-mode.el, aider.el
There is existing refactoring tool in emacs such as emr: https://github.com/emacsmirror/emr, but it only apply to very few program languages. LLM and aider make it possible to use AI to perform code refactoring, especially when the change is limited to few files. I personally use aider did code refactoring and feel recently LLM is capable for this. This PR adopt couple of refactoring techniques from [Martin Fowler's book](https://www.amazon.com/Refactoring-Improving-Existing-Addison-Wesley-Signature/dp/0134757599/ref=asc_df_0134757599?mcid=2eb8b1a5039a3b7c889ee081fc2132e0&hvocijid=16400341203663661896-0134757599-&hvexpln=73&tag=hyprod-20&linkCode=df0&hvadid=721245378154&hvpos=&hvnetw=g&hvrand=16400341203663661896&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9032161&hvtargid= …
=> Feat: Apply famous refactoring techniques from Martin Fowler's book.

HISTORY.org, README.org, README.zh-cn.org, aider-core.el, aider-doom.el, aider-prompt-mode.el, aider.el, etc/aider-etc.el
Addressing https://github.com/tninja/aider.el/issues/117
@Spike-Leung PTAL Thanks
=> Refact: Use comint-send-input since it is a more standard way

HISTORY.org, README.org, aider-code-change.el, aider-core.el, aider.el
This came from [Test Driven Development book](https://www.amazon.com/Test-Driven-Development-Kent-Beck/dp/0321146530), By Kent Beck.
To help code quality and test coverage, in a prompt driven development era.
Use aider to assist TDD loop, to help code quality in a prompt driven development era:
1. Red (Write failing test)
2. Green (Make test pass) 
3. Refactor (Improve code quality)
Other improve: switch to aider buffer will automatically scroll to bottom
=> Feat | AI assisted TDD cycle (Experimental)

HISTORY.org, aider-agile.el, aider-core.el
Sometime we need suggestion on how to improve the current code. This menu item is about that.
After aider provided suggestion, we can use 'go ahead' to accept the change, or provide our own opinion on how to refactor, using /ask
Also using it to refactor part of the aider-agile.el (function too long)
Make TDD refactoring stage call aider-refactor-book-method, and tell it to pass all tests
=> Feat: Add [Suggest Refactoring Strategy] menu item in the code refactoring tool, in the top.

aider-file.el, aider-helm.el
Initial prompt for code review function (aider-pull-or-review-diff-file), is only one sentence. This new prompt is more in detail, cover different aspects of code review, and have recommendation on each point. It generate better code review comments.
Press C-c a v to ask aider to do code review of the change.
=> Feat: Better prompt for code review of diff file

HISTORY.org, aider-agile.el, aider-code-change.el, aider-discussion.el, aider.el
Similar to https://github.com/tninja/aider.el/pull/142, for other existing functions.
=> Feat: Improve initial prompt to various functions

HISTORY.org, README.org, aider-code-change.el, aider-core.el, aider.el
1. Add recently added aider command, "/reasoning-effort" and "/think-tokens", to keyword highlight
2. aider-change-model will ask reasoning-effort for chatgpt o4,o3,o1 model, when it is main model change
3. README improvement
=> Refactor: Couple of small changes

HISTORY.org, aider-file.el, aider-prompt-mode.el
Verified the fix work as expected.
=> Fix: add function to resolve branch refs for remote branch handling

HISTORY.org, aider-core.el
Address https://github.com/tninja/aider.el/issues/159
The error message didn't show up again on my laptop. @velimir
Actually this change is from https://github.com/MatthewZMD/aidermacs/pull/131/files. cc @CeleritasCelery
=> Fix: Error during redisplay (jit-lock-function) when working with comint mode

HISTORY.org, aider-agile.el, aider-code-change.el, aider-core.el, aider-discussion.el, aider-file.el, aider-git.el, aider-software-planning.el, aider.el
Similar to https://github.com/tninja/aider.el/pull/185, but only keep validator functions.
=> Chore: Introduce shared validator functions to reduce duplicates

HISTORY.org, README.org, aider-doom.el, aider-legacy-code.el, aider-software-planning.el
Software Planning (C-c a P) is a useful feature for design discussion. It would be more useful to let it associate with some context in your repo, they could be:
1. Added files level (after adding all required files)
2. Single file (current buffer) level
3. Function (under cursor) level
4. Selected region level
=> Feat: Software Planning on given context

aider-core.el, aider-file.el, aider-git.el
For better readability and maintainability
=> Refactor: break large method into smaller ones

HISTORY.org, aider-git.el
to get diff between `<start commit> .. <end commit>`
=> Feat: commit range support for aider-pull-or-review-diff-file

HISTORY.org, README.org, aider-code-change.el
An enhancement to https://github.com/tninja/aider.el/pull/204
=> Feat: aider-function-or-region-change (C-c a r) support mult-line prompt in comments based code change 

HISTORY.org, aider-comint-markdown.el
Closing https://github.com/tninja/aider.el/issues/210
Thanks @blahgeek @vjohansen for reporting this issue and testing the solution!
=> Fix: do not use jit-lock-defer-time

README.org, best_practices.org
Addressing suggestion in https://github.com/tninja/aider.el/issues/218
=> doc: add best practices doc

aider-doom.el
Resolving https://github.com/tninja/aider.el/issues/226
Thanks @vlnn for the patch!
=> Double ESC in doom emacs kills aider process

aider-core.el
addressing https://github.com/tninja/aider.el/issues/228
@vjohansen PTAL Thanks
=> Chore: turn on visual-line-mode in aider comint buffer
